name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - name: git-ftp-action
      uses: sebastianpopp/git-ftp-action@2.1.0
      with:
        # URL
        url: ftp://ftp.u-php.de
        # FTP login name
        user: lars
        # FTP password
        password: 3105Madeira12
        # Specifies a local directory to sync from as if it were the git project root path.
        syncroot: # optional, default is .
      env:
        CI: true
